// Ed25519 public key used to verify license signatures (offline).
// Generated by scripts/keygen.mjs. The matching private key lives only in
// scripts/.license-private.key (gitignored) and never ships with the plugin.
export const LICENSE_PUBLIC_KEY = "yTeZPLeK99-pXMZmtZi4evkPBNIajW23emdSrBhLDQw";
